source "http://rubygems.org"
gem "net-ssh", "2.1.3"
gem "net-sftp", "2.0.5", :require => "net/sftp"
gem "activesupport", "3.0.5", :require => "active_support/all"
gem "i18n", "0.5.0"
gem "apachelogregex", "0.1.0"
gem "activerecord", "3.0.5", :require => "active_record"
gem "mysql2", "0.2.6"
gem "mysql", "2.8.1"
